import PDFDocument from "pdfkit";

export const generatePDF = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 60, bottom: 60, left: 60, right: 60 },
      info: {
        Author: "bratAI",
        Title: data.title,
        Creator: "bratAI",
      },
    });

    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (err) => reject(err));

    // Sleek Accent Bar at the Top
    doc.rect(0, 0, 595.28, 6).fill("#09090b");

    // Title Block
    doc.moveDown(1);
    doc.fillColor("#09090b").font("Helvetica-Bold").fontSize(32).text(data.title, 60, doc.y);
    
    if (data.subtitle) {
      doc.moveDown(0.3);
      doc.fillColor("#71717a").font("Helvetica").fontSize(14).text(data.subtitle);
    }

    doc.moveDown(1.5);
    
    // Separator
    doc.rect(60, doc.y, 475.28, 1).fill("#e4e4e7");
    doc.moveDown(2.5);

    // Document Sections
    data?.sections?.forEach((s) => {
      doc.fillColor("#09090b").font("Helvetica-Bold").fontSize(18).text(s.heading);
      doc.moveDown(0.75);

      s.points.forEach((p) => {
        doc
          .fillColor("#27272a")
          .font("Helvetica")
          .fontSize(11)
          .text("•   " + p, {
            lineGap: 6,
            paragraphGap: 6,
          });
      });

      doc.moveDown(1.5);
    });

    // Footer
    doc.moveDown(2);
    // Draw a bottom separator for the footer
    if (doc.y > 750) doc.addPage();
    doc.rect(60, doc.y, 475.28, 1).fill("#e4e4e7");
    doc.moveDown(1);
    doc
      .fillColor("#a1a1aa")
      .font("Helvetica")
      .fontSize(9)
      .text("Generated by bratAI", {
        align: "center",
      });

    // Sleek Accent Bar at the Bottom
    doc.rect(0, 841.89 - 6, 595.28, 6).fill("#09090b");

    doc.end();
  });
};
