import pptxgenjs from "pptxgenjs";

const COLORS = {
  primary: "09090B",   // zinc-950
  secondary: "18181B", // zinc-900
  text: "27272A",      // zinc-800
  light: "FAFAFA",     // zinc-50
  border: "E4E4E7",    // zinc-200
  white: "FFFFFF",
  muted: "A1A1AA",     // zinc-400
};

export const generatePPT = async (data) => {
  const ppt = new pptxgenjs();
  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "bratAI";
  ppt.title = data.title;
  ppt.subject = data.title;
  ppt.company = "bratAI";
  ppt.theme = {
    headFontFace: "Aptos",
    bodyFontFace: "Aptos",
    lang: "en-US",
  };

  addCover(ppt, data);

  data?.slides?.forEach((s, i) => {
    addContentSlide(ppt, s.title, s.points, i + 1, data.slides.length);
  });

  addThankYou(ppt);
  return ppt;
};

const addCover = (ppt, data) => {
  const slide = ppt.addSlide();
  slide.background = {
    color: COLORS.primary,
  };

  slide.addShape(ppt.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 13.33,
    h: 0.18,
    fill: {
      color: "27272A",
    },
    line: {
      color: "27272A",
    },
  });

  slide.addText(data.title, {
    x: 0.7,
    y: 1.7,
    w: 12,
    h: 0.8,
    align: "center",
    color: COLORS.white,
    bold: true,
    fontSize: 28,
  });

  slide.addText(data.subtitle, {
    x: 1,
    y: 2.8,
    w: 11.5,
    h: 0.4,
    align: "center",
    color: "A1A1AA",
    fontSize: 15,
  });

  slide.addText("Generated By bratAI", {
    x: 0,
    y: 6.9,
    w: 13.33,
    h: 0.2,
    align: "center",
    color: "71717A",
    fontSize: 10,
  });
};

const addContentSlide = (ppt, title, points, page, total) => {
  const slide = ppt.addSlide();
  slide.background = {
    color: COLORS.white,
  };

  slide.addText(title, {
    x: 0.6,
    y: 0.35,
    w: 10,
    h: 0.4,
    color: COLORS.primary,
    bold: true,
    fontSize: 24,
  });

  slide.addShape(ppt.ShapeType.line, {
    x: 0.6,
    y: 0.85,
    w: 12,
    h: 0,
    line: {
      color: COLORS.border,
      width: 1.2,
    },
  });

  const visiblePoints = points.slice(0, 6);

  visiblePoints.forEach((point, index) => {
    const y = 1.2 + index * 0.75;

    slide.addShape(ppt.ShapeType.roundRect, {
      x: 0.7,
      y,
      w: 12,
      h: 0.58,
      fill: {
        color: index % 2 ? "FAFAFA" : "F4F4F5",
      },
      line: {
        color: COLORS.border,
      },
      radius: 0.08,
    });

    slide.addShape(ppt.ShapeType.ellipse, {
      x: 0.92,
      y: y + 0.18,
      w: 0.12,
      h: 0.12,
      fill: {
        color: COLORS.primary,
      },
      line: {
        color: COLORS.primary,
      },
    });

    slide.addText(point, {
      x: 1.2,
      y: y + 0.08,
      w: 11,
      h: 0.35,
      fontSize: 15,
      color: COLORS.text,
      fit: "shrink",
    });

    slide.addText(`${page}/${total}`, {
      x: 12.1,
      y: 6.9,
      w: 0.8,
      h: 0.2,
      align: "right",
      fontSize: 10,
      color: COLORS.muted,
    });

    slide.addText(`bratAI`, {
      x: 0.6,
      y: 6.9,
      w: 2,
      h: 0.2,
      fontSize: 10,
      color: COLORS.muted,
    });
  });
};

const addThankYou = (ppt) => {
  const slide = ppt.addSlide();

  slide.background = {
    color: COLORS.secondary,
  };

  slide.addText(`Thank You`, {
    x: 0,
    y: 2.2,
    w: 13.33,
    h: 0.8,
    align: "center",
    color: COLORS.white,
    fontSize: 34,
    bold: true,
  });

  slide.addText(`Generated By bratAI`, {
    x: 0,
    y: 6.9,
    w: 13.33,
    h: 0.2,
    align: "center",
    color: "71717A",
    fontSize: 10,
  });
};
