name: brat ai deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Gateway
        run: |
          docker build \
          -f backend/gateway/Dockerfile \
          -t gateway backend

      - name: Tag Gateway
        run: |
          docker tag gateway:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/gateway:latest

      - name: Push Gateway
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/gateway:latest

      - name: Inject Firebase Credentials
        run: |
          # This creates the file dynamically in the runner
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > backend/services/auth/serviceAccountKey.json

      - name: Build Auth Service
        run: |
          docker build \
          -f backend/services/auth/Dockerfile \
          -t auth-service backend

      - name: Tag Auth Service
        run: |
          docker tag auth-service:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest

      - name: Push Auth Service
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest

      - name: Build Chat Service
        run: |
          docker build \
          -f backend/services/chat/Dockerfile \
          -t chat-service backend

      - name: Tag Chat Service
        run: |
          docker tag chat-service:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/chat-service:latest

      - name: Push Chat Service
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/chat-service:latest

      - name: Build Agent Service
        run: |
          docker build \
          -f backend/services/agent/Dockerfile \
          -t agent-service backend

      - name: Tag Agent Service
        run: |
          docker tag agent-service:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/agent-service:latest

      - name: Push Agent Service
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/agent-service:latest

      - name: Build Billing Service
        run: |
          docker build \
          -f backend/services/billing/Dockerfile \
          -t billing-service backend

      - name: Tag Billing Service
        run: |
          docker tag billing-service:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/billing-service:latest

      - name: Push Billing Service
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/billing-service:latest

      - name: Deploy Gateway
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER }} \
          --service ${{ secrets.GATEWAY_SERVICE}} \
          --force-new-deployment

      - name: Deploy Auth Service
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER }} \
          --service ${{ secrets.AUTH_SERVICE}} \
          --force-new-deployment

      - name: Deploy Chat Service
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER }} \
          --service ${{ secrets.CHAT_SERVICE}} \
          --force-new-deployment

      - name: Deploy Agent Service
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER }} \
          --service ${{ secrets.AGENT_SERVICE}} \
          --force-new-deployment

      - name: Deploy Billing Service
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER }} \
          --service ${{ secrets.BILLING_SERVICE}} \
          --force-new-deployment

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build frontend
        run: |
          cd frontend 
          npm install
          npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_RAZORPAY_KEY_ID: ${{ secrets.VITE_RAZORPAY_KEY_ID }}

      - name: AWS configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 sync \
          frontend/dist \
          s3://${{ secrets.S3_BUCKET }} \
          --delete

      - name: CloudFront invalidation
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"
